package com.Despachos.Facturacion;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * DetallefacturaId generated by hbm2java
 */
public class DetallefacturaId  implements java.io.Serializable {


     private int facturaIdFactura;
     private int facturaPersonaIdPersona;
     private int facturaExpedienteIdExpediente;
     private int facturaExpedienteTipoExpedienteIdTipoExpediente;

    public DetallefacturaId() {
    }

    public DetallefacturaId(int facturaIdFactura, int facturaPersonaIdPersona, int facturaExpedienteIdExpediente, int facturaExpedienteTipoExpedienteIdTipoExpediente) {
       this.facturaIdFactura = facturaIdFactura;
       this.facturaPersonaIdPersona = facturaPersonaIdPersona;
       this.facturaExpedienteIdExpediente = facturaExpedienteIdExpediente;
       this.facturaExpedienteTipoExpedienteIdTipoExpediente = facturaExpedienteTipoExpedienteIdTipoExpediente;
    }
   
    public int getFacturaIdFactura() {
        return this.facturaIdFactura;
    }
    
    public void setFacturaIdFactura(int facturaIdFactura) {
        this.facturaIdFactura = facturaIdFactura;
    }
    public int getFacturaPersonaIdPersona() {
        return this.facturaPersonaIdPersona;
    }
    
    public void setFacturaPersonaIdPersona(int facturaPersonaIdPersona) {
        this.facturaPersonaIdPersona = facturaPersonaIdPersona;
    }
    public int getFacturaExpedienteIdExpediente() {
        return this.facturaExpedienteIdExpediente;
    }
    
    public void setFacturaExpedienteIdExpediente(int facturaExpedienteIdExpediente) {
        this.facturaExpedienteIdExpediente = facturaExpedienteIdExpediente;
    }
    public int getFacturaExpedienteTipoExpedienteIdTipoExpediente() {
        return this.facturaExpedienteTipoExpedienteIdTipoExpediente;
    }
    
    public void setFacturaExpedienteTipoExpedienteIdTipoExpediente(int facturaExpedienteTipoExpedienteIdTipoExpediente) {
        this.facturaExpedienteTipoExpedienteIdTipoExpediente = facturaExpedienteTipoExpedienteIdTipoExpediente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetallefacturaId) ) return false;
		 DetallefacturaId castOther = ( DetallefacturaId ) other; 
         
		 return (this.getFacturaIdFactura()==castOther.getFacturaIdFactura())
 && (this.getFacturaPersonaIdPersona()==castOther.getFacturaPersonaIdPersona())
 && (this.getFacturaExpedienteIdExpediente()==castOther.getFacturaExpedienteIdExpediente())
 && (this.getFacturaExpedienteTipoExpedienteIdTipoExpediente()==castOther.getFacturaExpedienteTipoExpedienteIdTipoExpediente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFacturaIdFactura();
         result = 37 * result + this.getFacturaPersonaIdPersona();
         result = 37 * result + this.getFacturaExpedienteIdExpediente();
         result = 37 * result + this.getFacturaExpedienteTipoExpedienteIdTipoExpediente();
         return result;
   }   


}


