package com.Despachos.Facturacion;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private int idFactura;
     private Factura factura;
     private String descripcion;
     private float costo;

    public Detallefactura() {
    }

    public Detallefactura(int idFactura, Factura factura, String descripcion, float costo) {
       this.idFactura = idFactura;
       this.factura = factura;
       this.descripcion = descripcion;
       this.costo = costo;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public float getCosto() {
        return this.costo;
    }
    
    public void setCosto(float costo) {
        this.costo = costo;
    }




}


