package com.Despachos.Facturacion;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private DetallefacturaId id;
     private Factura factura;
     private String descripcion;
     private float costo;

    public Detallefactura() {
    }

    public Detallefactura(DetallefacturaId id, Factura factura, String descripcion, float costo) {
       this.id = id;
       this.factura = factura;
       this.descripcion = descripcion;
       this.costo = costo;
    }
   
    public DetallefacturaId getId() {
        return this.id;
    }
    
    public void setId(DetallefacturaId id) {
        this.id = id;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public float getCosto() {
        return this.costo;
    }
    
    public void setCosto(float costo) {
        this.costo = costo;
    }




}


