package com.Despachos.Facturacion;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * FacturaId generated by hbm2java
 */
public class FacturaId  implements java.io.Serializable {


     private int idFactura;
     private int personaIdPersona;
     private int expedienteIdExpediente;
     private int expedienteTipoExpedienteIdTipoExpediente;

    public FacturaId() {
    }

    public FacturaId(int idFactura, int personaIdPersona, int expedienteIdExpediente, int expedienteTipoExpedienteIdTipoExpediente) {
       this.idFactura = idFactura;
       this.personaIdPersona = personaIdPersona;
       this.expedienteIdExpediente = expedienteIdExpediente;
       this.expedienteTipoExpedienteIdTipoExpediente = expedienteTipoExpedienteIdTipoExpediente;
    }
   
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
    public int getPersonaIdPersona() {
        return this.personaIdPersona;
    }
    
    public void setPersonaIdPersona(int personaIdPersona) {
        this.personaIdPersona = personaIdPersona;
    }
    public int getExpedienteIdExpediente() {
        return this.expedienteIdExpediente;
    }
    
    public void setExpedienteIdExpediente(int expedienteIdExpediente) {
        this.expedienteIdExpediente = expedienteIdExpediente;
    }
    public int getExpedienteTipoExpedienteIdTipoExpediente() {
        return this.expedienteTipoExpedienteIdTipoExpediente;
    }
    
    public void setExpedienteTipoExpedienteIdTipoExpediente(int expedienteTipoExpedienteIdTipoExpediente) {
        this.expedienteTipoExpedienteIdTipoExpediente = expedienteTipoExpedienteIdTipoExpediente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FacturaId) ) return false;
		 FacturaId castOther = ( FacturaId ) other; 
         
		 return (this.getIdFactura()==castOther.getIdFactura())
 && (this.getPersonaIdPersona()==castOther.getPersonaIdPersona())
 && (this.getExpedienteIdExpediente()==castOther.getExpedienteIdExpediente())
 && (this.getExpedienteTipoExpedienteIdTipoExpediente()==castOther.getExpedienteTipoExpedienteIdTipoExpediente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFactura();
         result = 37 * result + this.getPersonaIdPersona();
         result = 37 * result + this.getExpedienteIdExpediente();
         result = 37 * result + this.getExpedienteTipoExpedienteIdTipoExpediente();
         return result;
   }   


}


