package com.Despachos.Facturacion;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import com.Despachos.Expedientes.Expediente;
import com.Despachos.Personas.Persona;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private FacturaId id;
     private Persona persona;
     private Expediente expediente;
     private Date fechaCreacion;
     private float subtotal;
     private float iva;
     private float total;
     private String medioPago;
     private String estado;
     private boolean activo;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);

    public Factura() {
    }

	
    public Factura(FacturaId id, Persona persona, Expediente expediente, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo) {
        this.id = id;
        this.persona = persona;
        this.expediente = expediente;
        this.fechaCreacion = fechaCreacion;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.medioPago = medioPago;
        this.estado = estado;
        this.activo = activo;
    }
    public Factura(FacturaId id, Persona persona, Expediente expediente, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo, Set<Detallefactura> detallefacturas) {
       this.id = id;
       this.persona = persona;
       this.expediente = expediente;
       this.fechaCreacion = fechaCreacion;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.medioPago = medioPago;
       this.estado = estado;
       this.activo = activo;
       this.detallefacturas = detallefacturas;
    }
   
    public FacturaId getId() {
        return this.id;
    }
    
    public void setId(FacturaId id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


