package com.Expedientes.Juzgados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA



/**
 * Asuntojuzgado generated by hbm2java
 */
public class Asuntojuzgado  implements java.io.Serializable {


     private AsuntojuzgadoId id;
     private Juzgados juzgados;
     private Asuntojudicial asuntojudicial;
     private boolean activo;

    public Asuntojuzgado() {
    }

    public Asuntojuzgado(AsuntojuzgadoId id, Juzgados juzgados, Asuntojudicial asuntojudicial, boolean activo) {
       this.id = id;
       this.juzgados = juzgados;
       this.asuntojudicial = asuntojudicial;
       this.activo = activo;
    }
   
    public AsuntojuzgadoId getId() {
        return this.id;
    }
    
    public void setId(AsuntojuzgadoId id) {
        this.id = id;
    }
    public Juzgados getJuzgados() {
        return this.juzgados;
    }
    
    public void setJuzgados(Juzgados juzgados) {
        this.juzgados = juzgados;
    }
    public Asuntojudicial getAsuntojudicial() {
        return this.asuntojudicial;
    }
    
    public void setAsuntojudicial(Asuntojudicial asuntojudicial) {
        this.asuntojudicial = asuntojudicial;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


