package com.Expedientes.Juzgados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Asuntojudicial generated by hbm2java
 */
public class Asuntojudicial  implements java.io.Serializable {


     private Integer idAsuntoJudicial;
     private String descripcion;
     private boolean activo;
     private Set asuntojuzgados = new HashSet(0);

    public Asuntojudicial() {
    }

	
    public Asuntojudicial(String descripcion, boolean activo) {
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Asuntojudicial(String descripcion, boolean activo, Set asuntojuzgados) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.asuntojuzgados = asuntojuzgados;
    }
   
    public Integer getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }
    
    public void setIdAsuntoJudicial(Integer idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getAsuntojuzgados() {
        return this.asuntojuzgados;
    }
    
    public void setAsuntojuzgados(Set asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }




}


