package com.Expedientes.Juzgados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nombreDepartamento;
     private Set juzgadoses = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(String nombreDepartamento, Set juzgadoses) {
       this.nombreDepartamento = nombreDepartamento;
       this.juzgadoses = juzgadoses;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getJuzgadoses() {
        return this.juzgadoses;
    }
    
    public void setJuzgadoses(Set juzgadoses) {
        this.juzgadoses = juzgadoses;
    }




}


