package com.Expedientes.Juzgados;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * Juzgados generated by hbm2java
 */
public class Juzgados  implements java.io.Serializable {


     private JuzgadosId id;
     private Municipio municipio;
     private String descripcion;
     private String direccion;
     private int telefono;
     private Integer celular;

    public Juzgados() {
    }

	
    public Juzgados(JuzgadosId id, Municipio municipio, String descripcion, String direccion, int telefono) {
        this.id = id;
        this.municipio = municipio;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Juzgados(JuzgadosId id, Municipio municipio, String descripcion, String direccion, int telefono, Integer celular) {
       this.id = id;
       this.municipio = municipio;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
    }
   
    public JuzgadosId getId() {
        return this.id;
    }
    
    public void setId(JuzgadosId id) {
        this.id = id;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }




}


