package com.Expedientes.Juzgados;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * JuzgadosId generated by hbm2java
 */
public class JuzgadosId  implements java.io.Serializable {


     private int idJuzgados;
     private int municipioIdMunicipio;
     private int municipioDepartamentoIdDepartamento;

    public JuzgadosId() {
    }

    public JuzgadosId(int idJuzgados, int municipioIdMunicipio, int municipioDepartamentoIdDepartamento) {
       this.idJuzgados = idJuzgados;
       this.municipioIdMunicipio = municipioIdMunicipio;
       this.municipioDepartamentoIdDepartamento = municipioDepartamentoIdDepartamento;
    }
   
    public int getIdJuzgados() {
        return this.idJuzgados;
    }
    
    public void setIdJuzgados(int idJuzgados) {
        this.idJuzgados = idJuzgados;
    }
    public int getMunicipioIdMunicipio() {
        return this.municipioIdMunicipio;
    }
    
    public void setMunicipioIdMunicipio(int municipioIdMunicipio) {
        this.municipioIdMunicipio = municipioIdMunicipio;
    }
    public int getMunicipioDepartamentoIdDepartamento() {
        return this.municipioDepartamentoIdDepartamento;
    }
    
    public void setMunicipioDepartamentoIdDepartamento(int municipioDepartamentoIdDepartamento) {
        this.municipioDepartamentoIdDepartamento = municipioDepartamentoIdDepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JuzgadosId) ) return false;
		 JuzgadosId castOther = ( JuzgadosId ) other; 
         
		 return (this.getIdJuzgados()==castOther.getIdJuzgados())
 && (this.getMunicipioIdMunicipio()==castOther.getMunicipioIdMunicipio())
 && (this.getMunicipioDepartamentoIdDepartamento()==castOther.getMunicipioDepartamentoIdDepartamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdJuzgados();
         result = 37 * result + this.getMunicipioIdMunicipio();
         result = 37 * result + this.getMunicipioDepartamentoIdDepartamento();
         return result;
   }   


}


