package com.Expedientes.Juzgados;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * MunicipioId generated by hbm2java
 */
public class MunicipioId  implements java.io.Serializable {


     private int idMunicipio;
     private int departamentoIdDepartamento;

    public MunicipioId() {
    }

    public MunicipioId(int idMunicipio, int departamentoIdDepartamento) {
       this.idMunicipio = idMunicipio;
       this.departamentoIdDepartamento = departamentoIdDepartamento;
    }
   
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public int getDepartamentoIdDepartamento() {
        return this.departamentoIdDepartamento;
    }
    
    public void setDepartamentoIdDepartamento(int departamentoIdDepartamento) {
        this.departamentoIdDepartamento = departamentoIdDepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MunicipioId) ) return false;
		 MunicipioId castOther = ( MunicipioId ) other; 
         
		 return (this.getIdMunicipio()==castOther.getIdMunicipio())
 && (this.getDepartamentoIdDepartamento()==castOther.getDepartamentoIdDepartamento());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMunicipio();
         result = 37 * result + this.getDepartamentoIdDepartamento();
         return result;
   }   


}


