package com.Expedientes.Juzgados;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private MunicipioId id;
     private Departamento departamento;
     private String descripcion;
     private Set<Juzgados> juzgadoses = new HashSet<Juzgados>(0);

    public Municipio() {
    }

	
    public Municipio(MunicipioId id, Departamento departamento, String descripcion) {
        this.id = id;
        this.departamento = departamento;
        this.descripcion = descripcion;
    }
    public Municipio(MunicipioId id, Departamento departamento, String descripcion, Set<Juzgados> juzgadoses) {
       this.id = id;
       this.departamento = departamento;
       this.descripcion = descripcion;
       this.juzgadoses = juzgadoses;
    }
   
    public MunicipioId getId() {
        return this.id;
    }
    
    public void setId(MunicipioId id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Juzgados> getJuzgadoses() {
        return this.juzgadoses;
    }
    
    public void setJuzgadoses(Set<Juzgados> juzgadoses) {
        this.juzgadoses = juzgadoses;
    }




}


