package com.Despachos.Abogados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA



/**
 * AbogadoTipoabogadoId generated by hbm2java
 */
public class AbogadoTipoabogadoId  implements java.io.Serializable {


     private int idTipoAbogado;
     private int idAbogado;

    public AbogadoTipoabogadoId() {
    }

    public AbogadoTipoabogadoId(int idTipoAbogado, int idAbogado) {
       this.idTipoAbogado = idTipoAbogado;
       this.idAbogado = idAbogado;
    }
   
    public int getIdTipoAbogado() {
        return this.idTipoAbogado;
    }
    
    public void setIdTipoAbogado(int idTipoAbogado) {
        this.idTipoAbogado = idTipoAbogado;
    }
    public int getIdAbogado() {
        return this.idAbogado;
    }
    
    public void setIdAbogado(int idAbogado) {
        this.idAbogado = idAbogado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbogadoTipoabogadoId) ) return false;
		 AbogadoTipoabogadoId castOther = ( AbogadoTipoabogadoId ) other; 
         
		 return (this.getIdTipoAbogado()==castOther.getIdTipoAbogado())
 && (this.getIdAbogado()==castOther.getIdAbogado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoAbogado();
         result = 37 * result + this.getIdAbogado();
         return result;
   }   


}


