package com.Despachos.Abogados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA



/**
 * AbogadoTipoabogado generated by hbm2java
 */
public class AbogadoTipoabogado  implements java.io.Serializable {


     private AbogadoTipoabogadoId id;
     private Tipoabogado tipoabogado;
     private Abogados abogados;
     private boolean activo;

    public AbogadoTipoabogado() {
    }

    public AbogadoTipoabogado(AbogadoTipoabogadoId id, Tipoabogado tipoabogado, Abogados abogados, boolean activo) {
       this.id = id;
       this.tipoabogado = tipoabogado;
       this.abogados = abogados;
       this.activo = activo;
    }
   
    public AbogadoTipoabogadoId getId() {
        return this.id;
    }
    
    public void setId(AbogadoTipoabogadoId id) {
        this.id = id;
    }
    public Tipoabogado getTipoabogado() {
        return this.tipoabogado;
    }
    
    public void setTipoabogado(Tipoabogado tipoabogado) {
        this.tipoabogado = tipoabogado;
    }
    public Abogados getAbogados() {
        return this.abogados;
    }
    
    public void setAbogados(Abogados abogados) {
        this.abogados = abogados;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


