package com.Despachos.Abogados;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoabogado generated by hbm2java
 */
public class Tipoabogado  implements java.io.Serializable {


     private Integer idTipoAbogado;
     private String descripcion;
     private Set abogadoTipoabogados = new HashSet(0);

    public Tipoabogado() {
    }

	
    public Tipoabogado(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipoabogado(String descripcion, Set abogadoTipoabogados) {
       this.descripcion = descripcion;
       this.abogadoTipoabogados = abogadoTipoabogados;
    }
   
    public Integer getIdTipoAbogado() {
        return this.idTipoAbogado;
    }
    
    public void setIdTipoAbogado(Integer idTipoAbogado) {
        this.idTipoAbogado = idTipoAbogado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getAbogadoTipoabogados() {
        return this.abogadoTipoabogados;
    }
    
    public void setAbogadoTipoabogados(Set abogadoTipoabogados) {
        this.abogadoTipoabogados = abogadoTipoabogados;
    }




}


