package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA

import com.Despachos.Abogados.AbogadosTipoAbogadosDAO;
import java.sql.SQLException;

/**
 * AbogadoTipoabogado generated by hbm2java
 */
public class AbogadoTipoabogado  implements java.io.Serializable {


     private Integer idAbogado;
     private Integer idtipoabogado;
     private boolean activo;
     private AbogadosTipoAbogadosDAO dao;
     
    public AbogadoTipoabogado() {
        
        dao = new AbogadosTipoAbogadosDAO();
    }

    public Integer getIdAbogado() {
        return idAbogado;
    }

    public void setIdAbogado(Integer idAbogado) {
        this.idAbogado = idAbogado;
    }

    public Integer getIdtipoabogado() {
        return idtipoabogado;
    }

    public void setIdtipoabogado(Integer idtipoabogado) {
        this.idtipoabogado = idtipoabogado;
    }
    
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    public void GuardarTipodeAbogado(AbogadoTipoabogado entidad) throws SQLException{
    
        dao.guardarTipoAbogado(entidad);
        
    }

 
}


