package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Asuntojudicial generated by hbm2java
 */
public class Asuntojudicial  implements java.io.Serializable {


     private Integer idAsuntoJudicial;
     private Tipoasunto tipoasunto;
     private String descripcion;
     private boolean activo;
     private Set<Asuntojuzgado> asuntojuzgados = new HashSet<Asuntojuzgado>(0);

    public Asuntojudicial() {
    }

	
    public Asuntojudicial(Tipoasunto tipoasunto, String descripcion, boolean activo) {
        this.tipoasunto = tipoasunto;
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Asuntojudicial(Tipoasunto tipoasunto, String descripcion, boolean activo, Set<Asuntojuzgado> asuntojuzgados) {
       this.tipoasunto = tipoasunto;
       this.descripcion = descripcion;
       this.activo = activo;
       this.asuntojuzgados = asuntojuzgados;
    }
   
    public Integer getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }
    
    public void setIdAsuntoJudicial(Integer idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }
    public Tipoasunto getTipoasunto() {
        return this.tipoasunto;
    }
    
    public void setTipoasunto(Tipoasunto tipoasunto) {
        this.tipoasunto = tipoasunto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Asuntojuzgado> getAsuntojuzgados() {
        return this.asuntojuzgados;
    }
    
    public void setAsuntojuzgados(Set<Asuntojuzgado> asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }




}


