package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estadoexpediente generated by hbm2java
 */
public class Estadoexpediente  implements java.io.Serializable {


     private Integer idEstadoExpediente;
     private String descripcion;
     private Date fechaEstado;
     private Set<Expediente> expedientes = new HashSet<Expediente>(0);

    public Estadoexpediente() {
    }

	
    public Estadoexpediente(String descripcion, Date fechaEstado) {
        this.descripcion = descripcion;
        this.fechaEstado = fechaEstado;
    }
    public Estadoexpediente(String descripcion, Date fechaEstado, Set<Expediente> expedientes) {
       this.descripcion = descripcion;
       this.fechaEstado = fechaEstado;
       this.expedientes = expedientes;
    }
   
    public Integer getIdEstadoExpediente() {
        return this.idEstadoExpediente;
    }
    
    public void setIdEstadoExpediente(Integer idEstadoExpediente) {
        this.idEstadoExpediente = idEstadoExpediente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaEstado() {
        return this.fechaEstado;
    }
    
    public void setFechaEstado(Date fechaEstado) {
        this.fechaEstado = fechaEstado;
    }
    public Set<Expediente> getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set<Expediente> expedientes) {
        this.expedientes = expedientes;
    }




}


