package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Estadoevolutivo generated by hbm2java
 */
public class Estadoevolutivo  implements java.io.Serializable {


     private Integer idEstado;
     private Usuarios usuarios;
     private Expediente expediente;
     private Tipoaviso tipoaviso;
     private Date fechaCreacion;
     private Date fechaCita;
     private String descripcion;
     private Date fechaAviso;
     private Date horaCita;
     private Date horaAviso;
     private String documento;

    public Estadoevolutivo() {
    }

	
    public Estadoevolutivo(Usuarios usuarios, Tipoaviso tipoaviso, Date fechaCreacion, Date fechaCita, String descripcion, Date fechaAviso, Date horaCita, Date horaAviso) {
        this.usuarios = usuarios;
        this.tipoaviso = tipoaviso;
        this.fechaCreacion = fechaCreacion;
        this.fechaCita = fechaCita;
        this.descripcion = descripcion;
        this.fechaAviso = fechaAviso;
        this.horaCita = horaCita;
        this.horaAviso = horaAviso;
    }
    public Estadoevolutivo(Usuarios usuarios, Expediente expediente, Tipoaviso tipoaviso, Date fechaCreacion, Date fechaCita, String descripcion, Date fechaAviso, Date horaCita, Date horaAviso, String documento) {
       this.usuarios = usuarios;
       this.expediente = expediente;
       this.tipoaviso = tipoaviso;
       this.fechaCreacion = fechaCreacion;
       this.fechaCita = fechaCita;
       this.descripcion = descripcion;
       this.fechaAviso = fechaAviso;
       this.horaCita = horaCita;
       this.horaAviso = horaAviso;
       this.documento = documento;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Tipoaviso getTipoaviso() {
        return this.tipoaviso;
    }
    
    public void setTipoaviso(Tipoaviso tipoaviso) {
        this.tipoaviso = tipoaviso;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaAviso() {
        return this.fechaAviso;
    }
    
    public void setFechaAviso(Date fechaAviso) {
        this.fechaAviso = fechaAviso;
    }
    public Date getHoraCita() {
        return this.horaCita;
    }
    
    public void setHoraCita(Date horaCita) {
        this.horaCita = horaCita;
    }
    public Date getHoraAviso() {
        return this.horaAviso;
    }
    
    public void setHoraAviso(Date horaAviso) {
        this.horaAviso = horaAviso;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }




}


