package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private Integer idExpediente;
     private Estadoexpediente estadoexpediente;
     private Usuarios usuarios;
     private Asuntojuzgado asuntojuzgado;
     private String descripcion;
     private Date fechaAlta;
     private Date fechaBaja;
     private int anio;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<Detallesexpediente> detallesexpedientes = new HashSet<Detallesexpediente>(0);
     private Set<Estadoevolutivo> estadoevolutivos = new HashSet<Estadoevolutivo>(0);

    public Expediente() {
    }

	
    public Expediente(Estadoexpediente estadoexpediente, Usuarios usuarios, Asuntojuzgado asuntojuzgado, String descripcion, Date fechaAlta, Date fechaBaja, int anio) {
        this.estadoexpediente = estadoexpediente;
        this.usuarios = usuarios;
        this.asuntojuzgado = asuntojuzgado;
        this.descripcion = descripcion;
        this.fechaAlta = fechaAlta;
        this.fechaBaja = fechaBaja;
        this.anio = anio;
    }
    public Expediente(Estadoexpediente estadoexpediente, Usuarios usuarios, Asuntojuzgado asuntojuzgado, String descripcion, Date fechaAlta, Date fechaBaja, int anio, Set<Factura> facturas, Set<Detallesexpediente> detallesexpedientes, Set<Estadoevolutivo> estadoevolutivos) {
       this.estadoexpediente = estadoexpediente;
       this.usuarios = usuarios;
       this.asuntojuzgado = asuntojuzgado;
       this.descripcion = descripcion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.anio = anio;
       this.facturas = facturas;
       this.detallesexpedientes = detallesexpedientes;
       this.estadoevolutivos = estadoevolutivos;
    }
   
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }
    public Estadoexpediente getEstadoexpediente() {
        return this.estadoexpediente;
    }
    
    public void setEstadoexpediente(Estadoexpediente estadoexpediente) {
        this.estadoexpediente = estadoexpediente;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Asuntojuzgado getAsuntojuzgado() {
        return this.asuntojuzgado;
    }
    
    public void setAsuntojuzgado(Asuntojuzgado asuntojuzgado) {
        this.asuntojuzgado = asuntojuzgado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<Detallesexpediente> getDetallesexpedientes() {
        return this.detallesexpedientes;
    }
    
    public void setDetallesexpedientes(Set<Detallesexpediente> detallesexpedientes) {
        this.detallesexpedientes = detallesexpedientes;
    }
    public Set<Estadoevolutivo> getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set<Estadoevolutivo> estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }




}


