package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Expediente expediente;
     private Personas personas;
     private Date fechaCreacion;
     private float subtotal;
     private float iva;
     private float total;
     private String medioPago;
     private String estado;
     private boolean activo;
     private Set<Detallefactura> detallefacturas = new HashSet<Detallefactura>(0);

    public Factura() {
    }

	
    public Factura(Expediente expediente, Personas personas, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo) {
        this.expediente = expediente;
        this.personas = personas;
        this.fechaCreacion = fechaCreacion;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.medioPago = medioPago;
        this.estado = estado;
        this.activo = activo;
    }
    public Factura(Expediente expediente, Personas personas, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo, Set<Detallefactura> detallefacturas) {
       this.expediente = expediente;
       this.personas = personas;
       this.fechaCreacion = fechaCreacion;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.medioPago = medioPago;
       this.estado = estado;
       this.activo = activo;
       this.detallefacturas = detallefacturas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Detallefactura> getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set<Detallefactura> detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


