package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Juzgados generated by hbm2java
 */
public class Juzgados  implements java.io.Serializable {


     private Integer idJuzgados;
     private Departamento departamento;
     private String descripcion;
     private String direccion;
     private int telefono;
     private Integer celular;
     private Set<Asuntojuzgado> asuntojuzgados = new HashSet<Asuntojuzgado>(0);

    public Juzgados() {
    }

	
    public Juzgados(Departamento departamento, String descripcion, String direccion, int telefono) {
        this.departamento = departamento;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.telefono = telefono;
    }
    public Juzgados(Departamento departamento, String descripcion, String direccion, int telefono, Integer celular, Set<Asuntojuzgado> asuntojuzgados) {
       this.departamento = departamento;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.asuntojuzgados = asuntojuzgados;
    }
   
    public Integer getIdJuzgados() {
        return this.idJuzgados;
    }
    
    public void setIdJuzgados(Integer idJuzgados) {
        this.idJuzgados = idJuzgados;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    public Set<Asuntojuzgado> getAsuntojuzgados() {
        return this.asuntojuzgados;
    }
    
    public void setAsuntojuzgados(Set<Asuntojuzgado> asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }




}


