package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA

import com.Despachos.Abogados.TipoAbogadosDAO;
import com.sun.org.apache.bcel.internal.generic.Select;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.faces.model.SelectItem;

/**
 * Tipoabogado generated by hbm2java
 */
public class Tipoabogado  implements java.io.Serializable {


     private int idTipoAbogado;
     private String descripcion;
     private TipoAbogadosDAO dao;

    public Tipoabogado() {
        
        dao = new TipoAbogadosDAO();
    }

    public int getIdTipoAbogado() {
        return idTipoAbogado;
    }

    public void setIdTipoAbogado(int idTipoAbogado) {
        this.idTipoAbogado = idTipoAbogado;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
   
      
     public ArrayList<SelectItem> listaTipoAbogados() throws SQLException{
        
        return dao.listarTipoAbogados();
        
    }

}


