package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoabogado generated by hbm2java
 */
public class Tipoabogado  implements java.io.Serializable {


     private Integer idTipoAbogado;
     private String descripcion;
     private Set<AbogadoTipoabogado> abogadoTipoabogados = new HashSet<AbogadoTipoabogado>(0);

    public Tipoabogado() {
    }

	
    public Tipoabogado(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipoabogado(String descripcion, Set<AbogadoTipoabogado> abogadoTipoabogados) {
       this.descripcion = descripcion;
       this.abogadoTipoabogados = abogadoTipoabogados;
    }
   
    public Integer getIdTipoAbogado() {
        return this.idTipoAbogado;
    }
    
    public void setIdTipoAbogado(Integer idTipoAbogado) {
        this.idTipoAbogado = idTipoAbogado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<AbogadoTipoabogado> getAbogadoTipoabogados() {
        return this.abogadoTipoabogados;
    }
    
    public void setAbogadoTipoabogados(Set<AbogadoTipoabogado> abogadoTipoabogados) {
        this.abogadoTipoabogados = abogadoTipoabogados;
    }




}


