package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoasunto generated by hbm2java
 */
public class Tipoasunto  implements java.io.Serializable {


     private Integer idTipoAsunto;
     private String descripcion;
     private boolean activo;
     private Set<Asuntojudicial> asuntojudicials = new HashSet<Asuntojudicial>(0);

    public Tipoasunto() {
    }

	
    public Tipoasunto(String descripcion, boolean activo) {
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Tipoasunto(String descripcion, boolean activo, Set<Asuntojudicial> asuntojudicials) {
       this.descripcion = descripcion;
       this.activo = activo;
       this.asuntojudicials = asuntojudicials;
    }
   
    public Integer getIdTipoAsunto() {
        return this.idTipoAsunto;
    }
    
    public void setIdTipoAsunto(Integer idTipoAsunto) {
        this.idTipoAsunto = idTipoAsunto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<Asuntojudicial> getAsuntojudicials() {
        return this.asuntojudicials;
    }
    
    public void setAsuntojudicials(Set<Asuntojudicial> asuntojudicials) {
        this.asuntojudicials = asuntojudicials;
    }




}


