package Entidades;
// Generated 08-28-2013 12:12:48 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoaviso generated by hbm2java
 */
public class Tipoaviso  implements java.io.Serializable {


     private Integer idTipoAviso;
     private String descripcion;
     private Set<Estadoevolutivo> estadoevolutivos = new HashSet<Estadoevolutivo>(0);

    public Tipoaviso() {
    }

	
    public Tipoaviso(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipoaviso(String descripcion, Set<Estadoevolutivo> estadoevolutivos) {
       this.descripcion = descripcion;
       this.estadoevolutivos = estadoevolutivos;
    }
   
    public Integer getIdTipoAviso() {
        return this.idTipoAviso;
    }
    
    public void setIdTipoAviso(Integer idTipoAviso) {
        this.idTipoAviso = idTipoAviso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Estadoevolutivo> getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set<Estadoevolutivo> estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }




}


