package com.Expedientes.Agenda;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import com.Expedientes.Juzgados.Usuarios;
import com.Despachos.Expedientes.Expediente;
import java.util.Date;

/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private AgendaId id;
     private Usuarios usuarios;
     private Expediente expediente;
     private String asunto;
     private Date fechaAsunto;
     private Date fechaAviso;
     private Date horaAsunto;
     private Date horaAviso;
     private String comentario;

    public Agenda() {
    }

    public Agenda(AgendaId id, Usuarios usuarios, Expediente expediente, String asunto, Date fechaAsunto, Date fechaAviso, Date horaAsunto, Date horaAviso, String comentario) {
       this.id = id;
       this.usuarios = usuarios;
       this.expediente = expediente;
       this.asunto = asunto;
       this.fechaAsunto = fechaAsunto;
       this.fechaAviso = fechaAviso;
       this.horaAsunto = horaAsunto;
       this.horaAviso = horaAviso;
       this.comentario = comentario;
    }
   
    public AgendaId getId() {
        return this.id;
    }
    
    public void setId(AgendaId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public Date getFechaAsunto() {
        return this.fechaAsunto;
    }
    
    public void setFechaAsunto(Date fechaAsunto) {
        this.fechaAsunto = fechaAsunto;
    }
    public Date getFechaAviso() {
        return this.fechaAviso;
    }
    
    public void setFechaAviso(Date fechaAviso) {
        this.fechaAviso = fechaAviso;
    }
    public Date getHoraAsunto() {
        return this.horaAsunto;
    }
    
    public void setHoraAsunto(Date horaAsunto) {
        this.horaAsunto = horaAsunto;
    }
    public Date getHoraAviso() {
        return this.horaAviso;
    }
    
    public void setHoraAviso(Date horaAviso) {
        this.horaAviso = horaAviso;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


