package com.Despachos.Expedientes;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * Asuntojudicial generated by hbm2java
 */
public class Asuntojudicial  implements java.io.Serializable {


     private Integer idAsuntoJudicial;
     private String descripcion;
     private boolean activo;

    public Asuntojudicial() {
    }

    public Asuntojudicial(String descripcion, boolean activo) {
       this.descripcion = descripcion;
       this.activo = activo;
    }
   
    public Integer getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }
    
    public void setIdAsuntoJudicial(Integer idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


