package com.Despachos.Expedientes;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import com.Expedientes.Juzgados.Usuarios;
import java.util.Date;

/**
 * Estadoevolutivo generated by hbm2java
 */
public class Estadoevolutivo  implements java.io.Serializable {


     private EstadoevolutivoId id;
     private Usuarios usuarios;
     private Expediente expediente;
     private Date fechaCreacion;
     private Date fechaCita;
     private String descripcion;
     private Date fechaAviso;
     private Date horaCita;
     private Date horaAviso;
     private String documento;
     private String tipoAviso;

    public Estadoevolutivo() {
    }

    public Estadoevolutivo(EstadoevolutivoId id, Usuarios usuarios, Expediente expediente, Date fechaCreacion, Date fechaCita, String descripcion, Date fechaAviso, Date horaCita, Date horaAviso, String documento, String tipoAviso) {
       this.id = id;
       this.usuarios = usuarios;
       this.expediente = expediente;
       this.fechaCreacion = fechaCreacion;
       this.fechaCita = fechaCita;
       this.descripcion = descripcion;
       this.fechaAviso = fechaAviso;
       this.horaCita = horaCita;
       this.horaAviso = horaAviso;
       this.documento = documento;
       this.tipoAviso = tipoAviso;
    }
   
    public EstadoevolutivoId getId() {
        return this.id;
    }
    
    public void setId(EstadoevolutivoId id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaCita() {
        return this.fechaCita;
    }
    
    public void setFechaCita(Date fechaCita) {
        this.fechaCita = fechaCita;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaAviso() {
        return this.fechaAviso;
    }
    
    public void setFechaAviso(Date fechaAviso) {
        this.fechaAviso = fechaAviso;
    }
    public Date getHoraCita() {
        return this.horaCita;
    }
    
    public void setHoraCita(Date horaCita) {
        this.horaCita = horaCita;
    }
    public Date getHoraAviso() {
        return this.horaAviso;
    }
    
    public void setHoraAviso(Date horaAviso) {
        this.horaAviso = horaAviso;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getTipoAviso() {
        return this.tipoAviso;
    }
    
    public void setTipoAviso(String tipoAviso) {
        this.tipoAviso = tipoAviso;
    }




}


