package com.Despachos.Expedientes;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * EstadoevolutivoId generated by hbm2java
 */
public class EstadoevolutivoId  implements java.io.Serializable {


     private int expedienteIdExpediente;
     private int expedienteTipoExpedienteIdTipoExpediente;
     private int usuariosIdUsuarios;

    public EstadoevolutivoId() {
    }

    public EstadoevolutivoId(int expedienteIdExpediente, int expedienteTipoExpedienteIdTipoExpediente, int usuariosIdUsuarios) {
       this.expedienteIdExpediente = expedienteIdExpediente;
       this.expedienteTipoExpedienteIdTipoExpediente = expedienteTipoExpedienteIdTipoExpediente;
       this.usuariosIdUsuarios = usuariosIdUsuarios;
    }
   
    public int getExpedienteIdExpediente() {
        return this.expedienteIdExpediente;
    }
    
    public void setExpedienteIdExpediente(int expedienteIdExpediente) {
        this.expedienteIdExpediente = expedienteIdExpediente;
    }
    public int getExpedienteTipoExpedienteIdTipoExpediente() {
        return this.expedienteTipoExpedienteIdTipoExpediente;
    }
    
    public void setExpedienteTipoExpedienteIdTipoExpediente(int expedienteTipoExpedienteIdTipoExpediente) {
        this.expedienteTipoExpedienteIdTipoExpediente = expedienteTipoExpedienteIdTipoExpediente;
    }
    public int getUsuariosIdUsuarios() {
        return this.usuariosIdUsuarios;
    }
    
    public void setUsuariosIdUsuarios(int usuariosIdUsuarios) {
        this.usuariosIdUsuarios = usuariosIdUsuarios;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EstadoevolutivoId) ) return false;
		 EstadoevolutivoId castOther = ( EstadoevolutivoId ) other; 
         
		 return (this.getExpedienteIdExpediente()==castOther.getExpedienteIdExpediente())
 && (this.getExpedienteTipoExpedienteIdTipoExpediente()==castOther.getExpedienteTipoExpedienteIdTipoExpediente())
 && (this.getUsuariosIdUsuarios()==castOther.getUsuariosIdUsuarios());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExpedienteIdExpediente();
         result = 37 * result + this.getExpedienteTipoExpedienteIdTipoExpediente();
         result = 37 * result + this.getUsuariosIdUsuarios();
         return result;
   }   


}


