package com.Despachos.Expedientes;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * ExpedienteId generated by hbm2java
 */
public class ExpedienteId  implements java.io.Serializable {


     private int idExpediente;
     private int tipoExpedienteIdTipoExpediente;

    public ExpedienteId() {
    }

    public ExpedienteId(int idExpediente, int tipoExpedienteIdTipoExpediente) {
       this.idExpediente = idExpediente;
       this.tipoExpedienteIdTipoExpediente = tipoExpedienteIdTipoExpediente;
    }
   
    public int getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }
    public int getTipoExpedienteIdTipoExpediente() {
        return this.tipoExpedienteIdTipoExpediente;
    }
    
    public void setTipoExpedienteIdTipoExpediente(int tipoExpedienteIdTipoExpediente) {
        this.tipoExpedienteIdTipoExpediente = tipoExpedienteIdTipoExpediente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExpedienteId) ) return false;
		 ExpedienteId castOther = ( ExpedienteId ) other; 
         
		 return (this.getIdExpediente()==castOther.getIdExpediente())
 && (this.getTipoExpedienteIdTipoExpediente()==castOther.getTipoExpedienteIdTipoExpediente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdExpediente();
         result = 37 * result + this.getTipoExpedienteIdTipoExpediente();
         return result;
   }   


}


