package com.Despachos.Expedientes;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private Integer idExpediente;
     private Tipoexpediente tipoexpediente;
     private String descripcion;
     private int idUsuarioCreacion;
     private Date fechaAlta;
     private Date fechaBaja;
     private int anio;
     private Set estadoevolutivos = new HashSet(0);

    public Expediente() {
    }

	
    public Expediente(Tipoexpediente tipoexpediente, String descripcion, int idUsuarioCreacion, Date fechaAlta, Date fechaBaja, int anio) {
        this.tipoexpediente = tipoexpediente;
        this.descripcion = descripcion;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.fechaAlta = fechaAlta;
        this.fechaBaja = fechaBaja;
        this.anio = anio;
    }
    public Expediente(Tipoexpediente tipoexpediente, String descripcion, int idUsuarioCreacion, Date fechaAlta, Date fechaBaja, int anio, Set estadoevolutivos) {
       this.tipoexpediente = tipoexpediente;
       this.descripcion = descripcion;
       this.idUsuarioCreacion = idUsuarioCreacion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.anio = anio;
       this.estadoevolutivos = estadoevolutivos;
    }
   
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }
    public Tipoexpediente getTipoexpediente() {
        return this.tipoexpediente;
    }
    
    public void setTipoexpediente(Tipoexpediente tipoexpediente) {
        this.tipoexpediente = tipoexpediente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdUsuarioCreacion() {
        return this.idUsuarioCreacion;
    }
    
    public void setIdUsuarioCreacion(int idUsuarioCreacion) {
        this.idUsuarioCreacion = idUsuarioCreacion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public Set getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }




}


