package com.Despachos.Expedientes;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import com.Expedientes.Agenda.Agenda;
import com.Despachos.Personas.PersonaTipopersona;
import com.Despachos.Facturacion.Factura;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Expediente generated by hbm2java
 */
public class Expediente  implements java.io.Serializable {


     private ExpedienteId id;
     private Tipoexpediente tipoexpediente;
     private String descripcion;
     private int idUsuarioCreacion;
     private Date fechaAlta;
     private Date fechaBaja;
     private int anio;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<PersonaTipopersona> personaTipopersonas = new HashSet<PersonaTipopersona>(0);
     private Set<Estadoevolutivo> estadoevolutivos = new HashSet<Estadoevolutivo>(0);
     private Set<Agenda> agendas = new HashSet<Agenda>(0);

    public Expediente() {
    }

	
    public Expediente(ExpedienteId id, Tipoexpediente tipoexpediente, String descripcion, int idUsuarioCreacion, Date fechaAlta, Date fechaBaja, int anio) {
        this.id = id;
        this.tipoexpediente = tipoexpediente;
        this.descripcion = descripcion;
        this.idUsuarioCreacion = idUsuarioCreacion;
        this.fechaAlta = fechaAlta;
        this.fechaBaja = fechaBaja;
        this.anio = anio;
    }
    public Expediente(ExpedienteId id, Tipoexpediente tipoexpediente, String descripcion, int idUsuarioCreacion, Date fechaAlta, Date fechaBaja, int anio, Set<Factura> facturas, Set<PersonaTipopersona> personaTipopersonas, Set<Estadoevolutivo> estadoevolutivos, Set<Agenda> agendas) {
       this.id = id;
       this.tipoexpediente = tipoexpediente;
       this.descripcion = descripcion;
       this.idUsuarioCreacion = idUsuarioCreacion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.anio = anio;
       this.facturas = facturas;
       this.personaTipopersonas = personaTipopersonas;
       this.estadoevolutivos = estadoevolutivos;
       this.agendas = agendas;
    }
   
    public ExpedienteId getId() {
        return this.id;
    }
    
    public void setId(ExpedienteId id) {
        this.id = id;
    }
    public Tipoexpediente getTipoexpediente() {
        return this.tipoexpediente;
    }
    
    public void setTipoexpediente(Tipoexpediente tipoexpediente) {
        this.tipoexpediente = tipoexpediente;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getIdUsuarioCreacion() {
        return this.idUsuarioCreacion;
    }
    
    public void setIdUsuarioCreacion(int idUsuarioCreacion) {
        this.idUsuarioCreacion = idUsuarioCreacion;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<PersonaTipopersona> getPersonaTipopersonas() {
        return this.personaTipopersonas;
    }
    
    public void setPersonaTipopersonas(Set<PersonaTipopersona> personaTipopersonas) {
        this.personaTipopersonas = personaTipopersonas;
    }
    public Set<Estadoevolutivo> getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set<Estadoevolutivo> estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }
    public Set<Agenda> getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set<Agenda> agendas) {
        this.agendas = agendas;
    }




}


