package com.Despachos.Expedientes;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idUsuarios;
     private String alias;
     private String contrasena;
     private boolean activo;
     private Set estadoevolutivos = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int idUsuarios, String alias, String contrasena, boolean activo) {
        this.idUsuarios = idUsuarios;
        this.alias = alias;
        this.contrasena = contrasena;
        this.activo = activo;
    }
    public Usuarios(int idUsuarios, String alias, String contrasena, boolean activo, Set estadoevolutivos) {
       this.idUsuarios = idUsuarios;
       this.alias = alias;
       this.contrasena = contrasena;
       this.activo = activo;
       this.estadoevolutivos = estadoevolutivos;
    }
   
    public int getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(int idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }




}


