package com.Despachos.Clientes;
// Generated 08-24-2013 05:33:50 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer idPersona;
     private String nombrePersona;
     private String primerApellidoPersona;
     private String segundoApellidoPersona;
     private String cedulaPersona;
     private String direccionPersona;
     private int telefonoPersona;
     private int celularPersona;
     private String emailPersona;
     private String observaciones;
     private Date fechaCreacion;
     private Date fechaBaja;
     private Set facturas = new HashSet(0);
     private Set personaTipopersonas = new HashSet(0);

    public Personas() {
    }

	
    public Personas(String nombrePersona, String primerApellidoPersona, String cedulaPersona, String direccionPersona, int telefonoPersona, int celularPersona, String emailPersona, Date fechaCreacion, Date fechaBaja) {
        this.nombrePersona = nombrePersona;
        this.primerApellidoPersona = primerApellidoPersona;
        this.cedulaPersona = cedulaPersona;
        this.direccionPersona = direccionPersona;
        this.telefonoPersona = telefonoPersona;
        this.celularPersona = celularPersona;
        this.emailPersona = emailPersona;
        this.fechaCreacion = fechaCreacion;
        this.fechaBaja = fechaBaja;
    }
    public Personas(String nombrePersona, String primerApellidoPersona, String segundoApellidoPersona, String cedulaPersona, String direccionPersona, int telefonoPersona, int celularPersona, String emailPersona, String observaciones, Date fechaCreacion, Date fechaBaja, Set facturas, Set personaTipopersonas) {
       this.nombrePersona = nombrePersona;
       this.primerApellidoPersona = primerApellidoPersona;
       this.segundoApellidoPersona = segundoApellidoPersona;
       this.cedulaPersona = cedulaPersona;
       this.direccionPersona = direccionPersona;
       this.telefonoPersona = telefonoPersona;
       this.celularPersona = celularPersona;
       this.emailPersona = emailPersona;
       this.observaciones = observaciones;
       this.fechaCreacion = fechaCreacion;
       this.fechaBaja = fechaBaja;
       this.facturas = facturas;
       this.personaTipopersonas = personaTipopersonas;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    public String getPrimerApellidoPersona() {
        return this.primerApellidoPersona;
    }
    
    public void setPrimerApellidoPersona(String primerApellidoPersona) {
        this.primerApellidoPersona = primerApellidoPersona;
    }
    public String getSegundoApellidoPersona() {
        return this.segundoApellidoPersona;
    }
    
    public void setSegundoApellidoPersona(String segundoApellidoPersona) {
        this.segundoApellidoPersona = segundoApellidoPersona;
    }
    public String getCedulaPersona() {
        return this.cedulaPersona;
    }
    
    public void setCedulaPersona(String cedulaPersona) {
        this.cedulaPersona = cedulaPersona;
    }
    public String getDireccionPersona() {
        return this.direccionPersona;
    }
    
    public void setDireccionPersona(String direccionPersona) {
        this.direccionPersona = direccionPersona;
    }
    public int getTelefonoPersona() {
        return this.telefonoPersona;
    }
    
    public void setTelefonoPersona(int telefonoPersona) {
        this.telefonoPersona = telefonoPersona;
    }
    public int getCelularPersona() {
        return this.celularPersona;
    }
    
    public void setCelularPersona(int celularPersona) {
        this.celularPersona = celularPersona;
    }
    public String getEmailPersona() {
        return this.emailPersona;
    }
    
    public void setEmailPersona(String emailPersona) {
        this.emailPersona = emailPersona;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getPersonaTipopersonas() {
        return this.personaTipopersonas;
    }
    
    public void setPersonaTipopersonas(Set personaTipopersonas) {
        this.personaTipopersonas = personaTipopersonas;
    }




}


