package com.Despachos.Personas;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA



/**
 * PersonaTipopersonaId generated by hbm2java
 */
public class PersonaTipopersonaId  implements java.io.Serializable {


     private int idTipoPersona;
     private int idPersona;

    public PersonaTipopersonaId() {
    }

    public PersonaTipopersonaId(int idTipoPersona, int idPersona) {
       this.idTipoPersona = idTipoPersona;
       this.idPersona = idPersona;
    }
   
    public int getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(int idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PersonaTipopersonaId) ) return false;
		 PersonaTipopersonaId castOther = ( PersonaTipopersonaId ) other; 
         
		 return (this.getIdTipoPersona()==castOther.getIdTipoPersona())
 && (this.getIdPersona()==castOther.getIdPersona());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoPersona();
         result = 37 * result + this.getIdPersona();
         return result;
   }   


}


