package com.Despachos.Personas;
// Generated 08-20-2013 07:07:18 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipopersona generated by hbm2java
 */
public class Tipopersona  implements java.io.Serializable {


     private Integer idTipoPersona;
     private String descripcionTipoPersona;
     private boolean activo;
     private Set<PersonaTipopersona> personaTipopersonas = new HashSet<PersonaTipopersona>(0);

    public Tipopersona() {
    }

	
    public Tipopersona(String descripcionTipoPersona, boolean activo) {
        this.descripcionTipoPersona = descripcionTipoPersona;
        this.activo = activo;
    }
    public Tipopersona(String descripcionTipoPersona, boolean activo, Set<PersonaTipopersona> personaTipopersonas) {
       this.descripcionTipoPersona = descripcionTipoPersona;
       this.activo = activo;
       this.personaTipopersonas = personaTipopersonas;
    }
   
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    public String getDescripcionTipoPersona() {
        return this.descripcionTipoPersona;
    }
    
    public void setDescripcionTipoPersona(String descripcionTipoPersona) {
        this.descripcionTipoPersona = descripcionTipoPersona;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set<PersonaTipopersona> getPersonaTipopersonas() {
        return this.personaTipopersonas;
    }
    
    public void setPersonaTipopersonas(Set<PersonaTipopersona> personaTipopersonas) {
        this.personaTipopersonas = personaTipopersonas;
    }




}


